package com.baran.recon.application.run;

import java.lang.management.ManagementFactory;
import java.lang.management.MemoryPoolMXBean;
import java.lang.management.MemoryType;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.DayOfWeek;
import java.time.Duration;
import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import com.baran.recon.application.port.LedgerEntryStore;
import com.baran.recon.application.port.RunStore;
import com.baran.recon.application.port.StageAStore;
import com.baran.recon.domain.run.ReconciliationRun;
import com.baran.recon.domain.run.RunStatus;
import com.baran.recon.support.ReconPostgres;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * NFR-PERF-2: Stage A for 1,000,000 PSP lines against 1,000,000 ledger entries, by a JVM limited to
 * 512 MB of heap, measured rather than estimated. Runs only under -Pperf, which sets -Xmx512m for the
 * test JVM; the test refuses to measure without it.
 *
 * <p>The items are synthetic and written straight into a database of the test's own, generated by
 * PostgreSQL itself, so the load costs the JVM nothing and is not timed. Of each million, by item
 * number: 900,000 pairs share a reference and an amount (A1); 50,000 pairs have no reference on the
 * line and an amount no other item has (A3); 20,000 lines carry their entry's reference with another
 * amount (AMOUNT_MISMATCH, the entry named by it); 15,000 lines carry a reference no entry has and an
 * amount no entry has (MISSING_IN_LEDGER), beside 15,000 entries no line names (MISSING_IN_PSP); and
 * 15,000 lines repeat a reference two by two (DUPLICATE_LINE), their entries left unmatched
 * (MISSING_IN_PSP). Every value date is a business day of September 2026, past every grace period at
 * the fixed run time. The tables are analysed after the load, as autovacuum would after such a load,
 * so the plans do not depend on when its daemon last woke.
 *
 * <p>The clock covers the whole run, from the call that records it RUNNING to its return, COMPLETED:
 * the stores are timed through proxies, so the result also says where the time went, statement by
 * statement, and how long the commit took (everything after COMPLETED is written).
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE, properties = {
        "recon.sources[0].code=PSP_STAGE_A_PERF",
        "recon.sources[0].type=PSP_SETTLEMENT"})
@ActiveProfiles("test")
@Import({FixedRunClock.class, StageAPerformanceTest.TimeTheStores.class})
@DirtiesContext
@Tag("perf")
@DisplayName("NFR-PERF-2: Stage A over 1,000,000 PSP lines and 1,000,000 ledger entries under -Xmx512m")
class StageAPerformanceTest {

    /** NFR-PERF-2 (TDD 4.6). A miss fails this test; the numbers are printed first either way. */
    private static final Duration TARGET = Duration.ofSeconds(120);
    private static final long MAX_HEAP = 512L * 1024 * 1024;
    private static final String SOURCE = "PSP_STAGE_A_PERF";
    private static final LocalDate FROM = LocalDate.of(2026, 9, 1);
    private static final LocalDate TO = LocalDate.of(2026, 9, 30);

    private static final int ITEMS = 1_000_000;
    /** The last item number of each group; see the class comment. */
    private static final int A1_LAST = 900_000;
    private static final int A3_LAST = 950_000;
    private static final int MISMATCH_LAST = 970_000;
    private static final int MISSING_LAST = 985_000;
    /** A range of event ids no other test class uses (CLAUDE.md 7.3); the database is this class's own anyway. */
    private static final long EVENT_ID_BASE = 20_000_000_000L;

    /** Nanoseconds spent in each timed method, and when each was first called and last returned. */
    private static final Map<String, AtomicLong> SPENT = new ConcurrentHashMap<>();
    private static final Map<String, AtomicLong> FIRST_CALLED = new ConcurrentHashMap<>();
    private static final Map<String, AtomicLong> LAST_RETURNED = new ConcurrentHashMap<>();

    private static ReconPostgres database;

    @Autowired
    private RunMatching matching;

    @DynamicPropertySource
    static void database(DynamicPropertyRegistry registry) {
        database = ReconPostgres.throwaway();
        database.registerIn(registry);
    }

    @AfterAll
    static void stopDatabase() {
        database.close();
    }

    @Test
    @DisplayName("NFR-PERF-2: one run over a million lines and a million entries completes in 120 s or less, with the "
            + "heap capped at 512 MB")
    void millionItemsUnderTheHeapCap() throws Exception {
        assertThat(Runtime.getRuntime().maxMemory()).as("run under -Pperf, which sets -Xmx512m").isLessThanOrEqualTo(MAX_HEAP);
        long loadStart = System.nanoTime();
        load();
        double loadSeconds = seconds(System.nanoTime() - loadStart);
        resetPeaks();
        SPENT.clear();
        FIRST_CALLED.clear();
        LAST_RETURNED.clear();

        long start = System.nanoTime();
        ReconciliationRun run = matching.run(SOURCE, FROM, TO, "operator-001");
        long end = System.nanoTime();
        Duration elapsed = Duration.ofNanos(end - start);

        long peakHeap = peakHeapUsed();
        System.out.printf(Locale.ROOT, "NFR-PERF-2 RESULT: %d lines and %d entries, run %s in %.3f s (target %d s); "
                        + "max heap %d MB, peak heap used %d MB; %d processors, Java %s; load and analyse %.1f s%n",
                ITEMS, ITEMS, run.status(), elapsed.toNanos() / 1e9, TARGET.toSeconds(),
                Runtime.getRuntime().maxMemory() / (1024 * 1024), peakHeap / (1024 * 1024),
                Runtime.getRuntime().availableProcessors(), Runtime.version(), loadSeconds);
        System.out.printf(Locale.ROOT, "NFR-PERF-2 BREAKDOWN: RUNNING row %.3f s, A1 %.3f s, reference breaks %.3f s, "
                        + "A3 %.3f s, MATCHED_LATE %.3f s, grace breaks %.3f s, statistics %.3f s, commit %.3f s%n",
                seconds(FIRST_CALLED.get("matchByReference").get() - start), spent("matchByReference"),
                spent("openReferenceBreaks"), spent("matchByAmount"), spent("resolveMatchedLate"),
                spent("openGraceBreaks"), spent("itemTotals") + spent("countInScope") + spent("countWithoutValueDate"),
                seconds(end - LAST_RETURNED.get("recordOutcome").get()));

        assertThat(run.status()).isEqualTo(RunStatus.COMPLETED);
        assertThat(outcomes()).as("the run did the work the data was built for").containsExactlyInAnyOrderEntriesOf(expected());
        assertThat(elapsed).as("NFR-PERF-2").isLessThanOrEqualTo(TARGET);
    }

    /** What the groups of the class comment must give. */
    private static Map<String, Long> expected() {
        Map<String, Long> expected = new LinkedHashMap<>();
        expected.put("match A1_EXACT_REFERENCE", (long) A1_LAST);
        expected.put("match A3_FALLBACK_UNIQUE", (long) (A3_LAST - A1_LAST));
        expected.put("break AMOUNT_MISMATCH", (long) (MISMATCH_LAST - A3_LAST));
        expected.put("break DUPLICATE_LINE", (long) (ITEMS - MISSING_LAST));
        expected.put("break MISSING_IN_LEDGER", (long) (MISSING_LAST - MISMATCH_LAST));
        // The entries beside the lines with unknown references, and the entries of the repeated references.
        expected.put("break MISSING_IN_PSP", (long) (MISSING_LAST - MISMATCH_LAST + ITEMS - MISSING_LAST));
        return expected;
    }

    private static Map<String, Long> outcomes() throws SQLException {
        Map<String, Long> outcomes = new LinkedHashMap<>();
        try (Connection connection = database.connectAsMigrator();
             Statement statement = connection.createStatement()) {
            statement.execute("SET search_path TO " + ReconPostgres.SCHEMA);
            try (var rows = statement.executeQuery("""
                    SELECT 'match ' || rule_id AS outcome, count(*) FROM matches GROUP BY rule_id
                    UNION ALL
                    SELECT 'break ' || break_type, count(*) FROM breaks GROUP BY break_type
                    ORDER BY 1
                    """)) {
                while (rows.next()) {
                    outcomes.put(rows.getString(1), rows.getLong(2));
                }
            }
        }
        return outcomes;
    }

    /**
     * Writes the file row, the lines and the entries, then analyses the tables, as the owner of the
     * schema. Every value is fake; the item number decides an item's group, reference and amount.
     */
    private static void load() throws SQLException {
        List<LocalDate> businessDays = FROM.datesUntil(TO.plusDays(1))
                .filter(day -> day.getDayOfWeek() != DayOfWeek.SATURDAY && day.getDayOfWeek() != DayOfWeek.SUNDAY)
                .toList();
        UUID fileId = UUID.randomUUID();
        try (Connection connection = database.connectAsMigrator()) {
            connection.setAutoCommit(false);
            try (Statement statement = connection.createStatement()) {
                statement.execute("SET search_path TO " + ReconPostgres.SCHEMA);
            }
            try (PreparedStatement file = connection.prepareStatement("""
                    INSERT INTO statement_files (id, source_code, statement_reference, sha256, sanitized_filename,
                                                 size_bytes, line_count, status, error_summary, uploaded_by, received_at)
                    VALUES (?, ?, 'PERF-STAGE-A', repeat('0', 64), 'perf.csv', 0, ?, 'INGESTED', NULL, 'operator-001',
                            now())
                    """)) {
                file.setObject(1, fileId);
                file.setString(2, SOURCE);
                file.setInt(3, ITEMS);
                assertThat(file.executeUpdate()).isOne();
            }
            try (PreparedStatement lines = connection.prepareStatement(ITEMS_CTE + """
                    INSERT INTO psp_lines (id, file_id, source_code, line_id, reference, batch_id, type,
                                           transaction_date, value_date, gross_amount, fee_amount, net_amount, currency)
                    SELECT gen_random_uuid(), ?, ?, 'L-' || lpad(CAST(n AS TEXT), 7, '0'), line_reference,
                           'B-' || CAST(n % 1000 AS TEXT), 'PAYMENT', value_date, value_date, line_amount, 0,
                           line_amount, 'TRY'
                      FROM item
                    """)) {
                int next = bindItems(lines, businessDays);
                lines.setObject(next, fileId);
                lines.setString(next + 1, SOURCE);
                assertThat(lines.executeUpdate()).isEqualTo(ITEMS);
            }
            try (PreparedStatement entries = connection.prepareStatement(ITEMS_CTE + """
                    INSERT INTO ledger_entries (id, event_id, ledger_entry_id, transaction_id, account_id, source_code,
                                                amount, currency, tx_type, created_at, value_date, received_at)
                    SELECT gen_random_uuid(), ? + n, ? + n, transaction_id, CAST(? AS UUID), ?, entry_amount, 'TRY',
                           'PAYMENT', CAST(value_date AS TIMESTAMP) AT TIME ZONE 'Europe/Istanbul' + INTERVAL '12 hours',
                           value_date, now()
                      FROM item
                    """)) {
                int next = bindItems(entries, businessDays);
                entries.setLong(next, EVENT_ID_BASE);
                entries.setLong(next + 1, EVENT_ID_BASE);
                entries.setString(next + 2, "00000000-0000-4000-8000-0000000000a1");
                entries.setString(next + 3, SOURCE);
                assertThat(entries.executeUpdate()).isEqualTo(ITEMS);
            }
            connection.commit();
            connection.setAutoCommit(true);
            try (Statement statement = connection.createStatement()) {
                statement.execute("ANALYZE statement_files, psp_lines, ledger_entries, match_items, matches, breaks");
            }
        }
    }

    /**
     * One row per item number: its value date, the reference its line carries, its entry's
     * transaction id, and the two amounts. A1's pairs share a reference and an amount; A3's lines have
     * no reference and share an amount found nowhere else; the other groups never meet.
     */
    private static final String ITEMS_CTE = """
            WITH numbered AS (
                SELECT n, CAST((CAST(? AS TEXT[]))[1 + (n - 1) % ?] AS DATE) AS value_date,
                       CAST('5f0c7a1e-0000-4000-8000-' || lpad(CAST(n AS TEXT), 12, '0') AS UUID) AS transaction_id
                  FROM generate_series(1, ?) AS n
            ),
            item AS (
                SELECT n, value_date, transaction_id,
                       CASE WHEN n <= ? THEN CAST(transaction_id AS TEXT)
                            WHEN n <= ? THEN NULL
                            WHEN n <= ? THEN CAST(transaction_id AS TEXT)
                            WHEN n <= ? THEN '6a0c7a1e-0000-4000-8000-' || lpad(CAST(n AS TEXT), 12, '0')
                            ELSE '5f0c7a1e-0000-4000-8000-' || lpad(CAST(n - (n - ? - 1) % 2 AS TEXT), 12, '0')
                       END AS line_reference,
                       CASE WHEN n <= ? THEN 10000 + n % 50000
                            WHEN n <= ? THEN 100000000 + n
                            WHEN n <= ? THEN 300000000 + n
                            WHEN n <= ? THEN 400000000 + n
                            ELSE 700000000 + n END AS line_amount,
                       CASE WHEN n <= ? THEN 10000 + n % 50000
                            WHEN n <= ? THEN 100000000 + n
                            WHEN n <= ? THEN 200000000 + n
                            WHEN n <= ? THEN 500000000 + n
                            ELSE 600000000 + n END AS entry_amount
                  FROM numbered
            )
            """;

    /** Binds ITEMS_CTE's parameters and returns the index of the next one. */
    private static int bindItems(PreparedStatement statement, List<LocalDate> businessDays) throws SQLException {
        int index = 1;
        statement.setArray(index++, statement.getConnection().createArrayOf("text",
                businessDays.stream().map(LocalDate::toString).toArray()));
        statement.setInt(index++, businessDays.size());
        statement.setInt(index++, ITEMS);
        for (int last : new int[] {A1_LAST, A3_LAST, MISMATCH_LAST, MISSING_LAST, MISSING_LAST}) {
            statement.setInt(index++, last);
        }
        for (int round = 0; round < 2; round++) {
            for (int last : new int[] {A1_LAST, A3_LAST, MISMATCH_LAST, MISSING_LAST}) {
                statement.setInt(index++, last);
            }
        }
        return index;
    }

    private static double spent(String method) {
        AtomicLong nanos = SPENT.get(method);
        return nanos == null ? 0 : seconds(nanos.get());
    }

    private static double seconds(long nanos) {
        return nanos / 1e9;
    }

    private static void resetPeaks() {
        ManagementFactory.getMemoryPoolMXBeans().forEach(MemoryPoolMXBean::resetPeakUsage);
    }

    /** The sum of each heap pool's peak, an upper bound on the heap used at any one moment. */
    private static long peakHeapUsed() {
        return ManagementFactory.getMemoryPoolMXBeans().stream()
                .filter(pool -> pool.getType() == MemoryType.HEAP)
                .mapToLong(pool -> pool.getPeakUsage().getUsed())
                .sum();
    }

    @TestConfiguration(proxyBeanMethods = false)
    static class TimeTheStores {

        @Bean
        static BeanPostProcessor timeStageAAndRunStores() {
            return new BeanPostProcessor() {
                @Override
                public Object postProcessAfterInitialization(Object bean, String beanName) {
                    Class<?> port = bean instanceof StageAStore ? StageAStore.class
                            : bean instanceof RunStore ? RunStore.class
                            : bean instanceof LedgerEntryStore ? LedgerEntryStore.class
                            : null;
                    if (port == null) {
                        return bean;
                    }
                    return Proxy.newProxyInstance(port.getClassLoader(), new Class<?>[] {port}, (proxy, method, args) -> {
                        long called = System.nanoTime();
                        FIRST_CALLED.computeIfAbsent(method.getName(), name -> new AtomicLong(called));
                        try {
                            return method.invoke(bean, args);
                        } catch (InvocationTargetException failure) {
                            throw failure.getCause();
                        } finally {
                            long returned = System.nanoTime();
                            SPENT.computeIfAbsent(method.getName(), name -> new AtomicLong()).addAndGet(returned - called);
                            LAST_RETURNED.computeIfAbsent(method.getName(), name -> new AtomicLong()).set(returned);
                        }
                    });
                }
            };
        }
    }
}
